services:
    stn_db:
        image: mysql
        command: --init-file /data/application/init.sql
        volumes:
            - ./init-db.sql:/data/application/init.sql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: stn
            MYSQL_PASSWORD: password
        ports:
            - 3368:3306
    stn_app:
        build:
            context: '.'
        restart: always
        container_name: stn-api
        ports:
            - 8899:80
        depends_on:
            - stn_db
        volumes:
            - /var/www/stn:/var/www/html
            - /var/www/stn/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
            - APACHE_RUN_USER=#1000
            - APACHE_RUN_GROUP=#1000
    redis:
        container_name: stn-redis
        image: 'redis:latest'
        ports:
            - '6378:6379'
