services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stn_app
    restart: always
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    networks:
      - stn_network
    environment:
      - REDIS_HOST=redis
      - DB_HOST=mysql


  db:
    image: mysql:8.0
    container_name: stn_db
    restart: always
    environment:
      MYSQL_DATABASE: stn
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - stn_network
    hostname: mysql


  redis:
    image: redis:alpine
    container_name: stn_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - stn_network

volumes:
  db_data:

networks:
  stn_network:
    driver: bridge
