name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Debug - Display SSH Key
        run: |
          echo "SSH Key:"
          echo "${{ secrets.SERVER_SSH_KEY }}"
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd /var/www/stn

            # Config git
            sudo git config --global --add safe.directory /var/www/stn

            # Pull the latest code from GitHub
            sudo git pull origin main

            # Copy environment file if needed
            if [ ! -f .env ]; then
              sudo cp /var/www/.env.local .env
            fi

            # Set proper permissions
            sudo chown -R www-data:www-data /var/www/stn
            sudo chmod -R 775 storage bootstrap/cache

            # Run Laravel commands inside the Docker container
            sudo docker-compose exec -T app composer install --no-dev --optimize-autoloader
            sudo docker-compose exec -T app php artisan migrate --force
            sudo docker-compose exec -T app php artisan db:seed --force
            sudo docker-compose exec -T app php artisan config:cache
            sudo docker-compose exec -T app php artisan route:cache
            sudo docker-compose exec -T app php artisan view:cache
            sudo docker-compose exec -T app php artisan storage:link

            # Restart supervisor workers
            sudo docker-compose exec -T app supervisorctl reread
            sudo docker-compose exec -T app supervisorctl update
            sudo docker-compose exec -T app supervisorctl start all

            # Ensure proper permissions after all operations
            sudo chown -R www-data:www-data /var/www/stn
            sudo chmod -R 775 storage bootstrap/cache

            # Reload Nginx configuration
            sudo systemctl reload nginx
