name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with: # Fixed indentation
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd /var/www/stn
            # Copy .env.local to .env (if you need to do that)
            sudo cp /var/www/.env.local /var/www/stn/.env
            # Pull the latest code from GitHub
            sudo git pull origin main
            # Set permissions for Laravel storage and cache
            sudo chown -R www-data:www-data /var/www/stn
            sudo chmod -R 775 /var/www/stn/storage /var/www/stn/bootstrap/cache
            # Run Docker Compose commands to start containers and handle cache
            sudo docker-compose -f /var/www/stn/docker-compose.yml up -d
            sudo docker-compose -f /var/www/stn/docker-compose.yml exec composer install --no-dev --prefer-dist --optimize-autoloader
            sudo docker-compose -f /var/www/stn/docker-compose.yml exec php artisan migrate --force
            sudo docker-compose -f /var/www/stn/docker-compose.yml exec php artisan config:cache
            sudo docker-compose -f /var/www/stn/docker-compose.yml exec php artisan route:cache
            sudo docker-compose -f /var/www/stn/docker-compose.yml exec php artisan view:cache
            # Restart nginx (if necessary)
            sudo systemctl restart nginx
