name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, bcmath, curl, xml

      - name: Install dependencies
        run: |
          composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Set up SSH
        run: |
          # Create the .ssh directory if it doesn't exist
          mkdir -p ~/.ssh
          # Add the private SSH key from GitHub secrets into the SSH file
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          # Set correct permissions for the private key file
          chmod 600 ~/.ssh/id_rsa
          # Disable strict host key checking (to avoid prompts)
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      - name: Deploy to Server
        run: |
          # SSH into the server and deploy the Laravel app
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Navigate to the project directory
            cd /var/www/stn
            # Copy .env.local to .env (if you need to do that)
            sudo cp /var/www/.env.local /var/www/stn/.env
            # Pull the latest code from GitHub
            git pull origin main
            # Set permissions for Laravel storage and cache
            sudo chown -R www-data:www-data /var/www/stn
            sudo chmod -R 775 /var/www/stn/storage /var/www/stn/bootstrap/cache
            # Run Docker Compose commands to start containers and handle cache
            sudo docker-compose -f /var/www/stn/docker-compose.yml up -d
            sudo docker-compose -f /var/www/stn/docker-compose.yml exec php-fpm composer install --no-dev --prefer-dist --optimize-autoloader
            sudo docker-compose -f /var/www/stn/docker-compose.yml exec php-fpm php artisan migrate --force
            sudo docker-compose -f /var/www/stn/docker-compose.yml exec php-fpm php artisan config:cache
            sudo docker-compose -f /var/www/stn/docker-compose.yml exec php-fpm php artisan route:cache
            sudo docker-compose -f /var/www/stn/docker-compose.yml exec php-fpm php artisan view:cache
            # Restart nginx (if necessary)
            sudo systemctl restart nginx
          EOF
